"""Curated marketplace catalog of well-known MCP servers.

Static data only: installing an entry persists a row in ``mcp_servers``
(``url_or_command`` = the install hint command).  The runtime MCP client —
actually spawning/connecting to these servers — is a later phase; until then
every privileged action still goes through the Rust permission broker
(ADR-003).  Descriptions, categories and permission notes are in French,
matching the product UI language.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final, Literal

McpTransport = Literal["stdio", "http"]

# Ordered list of catalog categories (French). ``categories()`` returns this;
# the marketplace UI renders sections in this order.
CATEGORIES: Final[tuple[str, ...]] = (
    "Système de fichiers & stockage",
    "Développement & code",
    "Bases de données",
    "Web, recherche & scraping",
    "Cloud & infra",
    "Communication",
    "Productivité & connaissance",
    "Paiement & business",
    "IA & données",
    "Outils & système",
)


@dataclass(frozen=True, slots=True)
class McpCatalogEntry:
    catalog_id: str
    name: str
    description: str
    category: str
    transport: McpTransport
    install_hint: str  # command used as url_or_command when installed
    permissions_note: str
    official: bool


CATALOG: Final[tuple[McpCatalogEntry, ...]] = (
    # ============================================ Système de fichiers & stockage
    McpCatalogEntry(
        catalog_id="filesystem",
        name="Filesystem",
        description="Lecture et écriture de fichiers dans les dossiers que vous autorisez.",
        category="Système de fichiers & stockage",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-filesystem <dossier>",
        permissions_note="Accède aux fichiers des dossiers autorisés uniquement.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="google-drive",
        name="Google Drive",
        description="Recherche et lecture de fichiers stockés sur Google Drive.",
        category="Système de fichiers & stockage",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-gdrive",
        permissions_note="Authentification Google ; accès en lecture à vos fichiers Drive.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="dropbox",
        name="Dropbox",
        description="Parcours, recherche et récupération de fichiers stockés sur Dropbox.",
        category="Système de fichiers & stockage",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-dropbox",
        permissions_note="Nécessite un jeton Dropbox ; accès à vos fichiers et dossiers.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="onedrive",
        name="OneDrive",
        description="Accès aux fichiers Microsoft OneDrive : recherche et lecture.",
        category="Système de fichiers & stockage",
        transport="stdio",
        install_hint="npx -y onedrive-mcp-server",
        permissions_note="Authentification Microsoft ; accès à vos fichiers OneDrive.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="box",
        name="Box",
        description="Gestion des fichiers et dossiers stockés sur Box.",
        category="Système de fichiers & stockage",
        transport="stdio",
        install_hint="uvx box-mcp-server",
        permissions_note="Authentification Box ; accès à vos fichiers d'entreprise.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="s3",
        name="Amazon S3",
        description="Lecture et écriture d'objets dans des buckets Amazon S3.",
        category="Système de fichiers & stockage",
        transport="stdio",
        install_hint="uvx awslabs.s3-mcp-server",
        permissions_note="Utilise vos identifiants AWS ; accès aux buckets S3 autorisés.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="gcs",
        name="Google Cloud Storage",
        description="Accès aux buckets et objets Google Cloud Storage.",
        category="Système de fichiers & stockage",
        transport="stdio",
        install_hint="npx -y gcs-mcp-server",
        permissions_note="Utilise vos identifiants GCP ; accès aux buckets autorisés.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="azure-blob",
        name="Azure Blob Storage",
        description="Lecture et écriture de blobs dans Azure Blob Storage.",
        category="Système de fichiers & stockage",
        transport="stdio",
        install_hint="npx -y azure-storage-mcp",
        permissions_note="Nécessite une chaîne de connexion Azure ; accès aux conteneurs.",
        official=False,
    ),
    # ================================================= Développement & code
    McpCatalogEntry(
        catalog_id="github",
        name="GitHub",
        description="Gestion des dépôts GitHub : issues, pull requests, fichiers et recherche.",
        category="Développement & code",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-github",
        permissions_note="Nécessite un jeton GitHub ; peut lire et modifier vos dépôts.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="gitlab",
        name="GitLab",
        description="Gestion des projets GitLab : issues, merge requests et fichiers.",
        category="Développement & code",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-gitlab",
        permissions_note="Nécessite un jeton GitLab ; peut lire et modifier vos projets.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="bitbucket",
        name="Bitbucket",
        description="Gestion des dépôts Bitbucket : pull requests, pipelines et fichiers.",
        category="Développement & code",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-bitbucket",
        permissions_note="Nécessite un jeton Bitbucket ; peut lire et modifier vos dépôts.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="git",
        name="Git",
        description="Opérations Git locales : historique, diff, commits et branches.",
        category="Développement & code",
        transport="stdio",
        install_hint="uvx mcp-server-git",
        permissions_note="Lit et modifie les dépôts Git locaux autorisés.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="docker",
        name="Docker",
        description="Gestion des conteneurs, images et volumes Docker locaux.",
        category="Développement & code",
        transport="stdio",
        install_hint="uvx mcp-server-docker",
        permissions_note="Contrôle le démon Docker local : création et arrêt de conteneurs.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="kubernetes",
        name="Kubernetes",
        description="Pilotage d'un cluster Kubernetes : pods, déploiements et logs.",
        category="Développement & code",
        transport="stdio",
        install_hint="npx -y mcp-server-kubernetes",
        permissions_note="Utilise votre kubeconfig ; peut modifier les ressources du cluster.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="jira",
        name="Jira",
        description="Gestion des tickets et projets Jira : création, recherche et transitions.",
        category="Développement & code",
        transport="stdio",
        install_hint="uvx mcp-atlassian",
        permissions_note="Nécessite un jeton Atlassian ; peut lire et modifier vos tickets.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="linear",
        name="Linear",
        description="Gestion des tickets et projets Linear.",
        category="Développement & code",
        transport="http",
        install_hint="npx -y mcp-remote https://mcp.linear.app/sse",
        permissions_note="Authentification Linear ; peut lire et modifier vos tickets.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="sentry",
        name="Sentry",
        description="Consultation des erreurs et problèmes remontés dans Sentry.",
        category="Développement & code",
        transport="stdio",
        install_hint="uvx mcp-server-sentry",
        permissions_note="Nécessite un jeton Sentry ; accès en lecture à vos projets.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="terraform",
        name="Terraform",
        description="Exploration de la configuration Terraform, des modules et du registry.",
        category="Développement & code",
        transport="stdio",
        install_hint="docker run -i --rm hashicorp/terraform-mcp-server",
        permissions_note="Lit vos configurations ; les plans/applies restent sous contrôle.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="ansible",
        name="Ansible",
        description="Exploration des playbooks, inventaires et rôles Ansible.",
        category="Développement & code",
        transport="stdio",
        install_hint="uvx ansible-mcp-server",
        permissions_note="Lit vos playbooks ; l'exécution reste sous votre contrôle.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="npm",
        name="npm Registry",
        description="Recherche de paquets npm, versions, dépendances et métadonnées.",
        category="Développement & code",
        transport="stdio",
        install_hint="npx -y npm-registry-mcp",
        permissions_note="Requêtes en lecture vers le registre npm public.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="pypi",
        name="PyPI",
        description="Recherche de paquets PyPI, versions et métadonnées Python.",
        category="Développement & code",
        transport="stdio",
        install_hint="uvx pypi-mcp-server",
        permissions_note="Requêtes en lecture vers l'index PyPI public.",
        official=False,
    ),
    # ===================================================== Bases de données
    McpCatalogEntry(
        catalog_id="postgres",
        name="PostgreSQL",
        description="Interrogation de bases PostgreSQL : schéma et requêtes SQL en lecture.",
        category="Bases de données",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-postgres <url-connexion>",
        permissions_note="Accès en lecture à la base indiquée par l'URL de connexion.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="mysql",
        name="MySQL",
        description="Interrogation de bases MySQL et MariaDB : schéma et requêtes SQL.",
        category="Bases de données",
        transport="stdio",
        install_hint="npx -y @benborla29/mcp-server-mysql",
        permissions_note="Accès à la base indiquée par les identifiants de connexion.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="sqlite",
        name="SQLite",
        description="Interrogation et analyse de fichiers de base SQLite.",
        category="Bases de données",
        transport="stdio",
        install_hint="uvx mcp-server-sqlite --db-path <fichier.db>",
        permissions_note="Lit et écrit dans le fichier de base indiqué.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="mongodb",
        name="MongoDB",
        description="Interrogation de bases MongoDB : collections, documents et agrégations.",
        category="Bases de données",
        transport="stdio",
        install_hint="npx -y mongodb-mcp-server",
        permissions_note="Accès à la base indiquée par la chaîne de connexion.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="redis",
        name="Redis",
        description="Lecture et écriture de clés dans une base Redis.",
        category="Bases de données",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-redis <url-connexion>",
        permissions_note="Accès en lecture/écriture à l'instance Redis indiquée.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="elasticsearch",
        name="Elasticsearch",
        description="Recherche et agrégations sur des index Elasticsearch.",
        category="Bases de données",
        transport="stdio",
        install_hint="npx -y @elastic/mcp-server-elasticsearch",
        permissions_note="Nécessite des identifiants Elasticsearch ; accès à vos index.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="clickhouse",
        name="ClickHouse",
        description="Requêtes analytiques SQL sur des bases ClickHouse.",
        category="Bases de données",
        transport="stdio",
        install_hint="uvx mcp-clickhouse",
        permissions_note="Accès en lecture à la base ClickHouse indiquée.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="snowflake",
        name="Snowflake",
        description="Interrogation de l'entrepôt de données Snowflake en SQL.",
        category="Bases de données",
        transport="stdio",
        install_hint="uvx mcp-snowflake-server",
        permissions_note="Utilise vos identifiants Snowflake ; accès à vos entrepôts.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="bigquery",
        name="BigQuery",
        description="Requêtes SQL sur l'entrepôt de données Google BigQuery.",
        category="Bases de données",
        transport="stdio",
        install_hint="uvx mcp-server-bigquery",
        permissions_note="Utilise vos identifiants GCP ; accès à vos jeux de données.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="supabase",
        name="Supabase",
        description="Gestion des projets Supabase : base Postgres, tables et migrations.",
        category="Bases de données",
        transport="stdio",
        install_hint="npx -y @supabase/mcp-server-supabase",
        permissions_note="Nécessite un jeton Supabase ; peut lire et modifier vos projets.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="neo4j",
        name="Neo4j",
        description="Interrogation de graphes Neo4j via le langage Cypher.",
        category="Bases de données",
        transport="stdio",
        install_hint="uvx mcp-neo4j-cypher",
        permissions_note="Accès à la base graphe indiquée par les identifiants.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="cassandra",
        name="Cassandra",
        description="Interrogation de bases Apache Cassandra distribuées (CQL).",
        category="Bases de données",
        transport="stdio",
        install_hint="uvx mcp-cassandra-server",
        permissions_note="Accès au cluster Cassandra indiqué par les identifiants.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="influxdb",
        name="InfluxDB",
        description="Requêtes sur des séries temporelles stockées dans InfluxDB.",
        category="Bases de données",
        transport="stdio",
        install_hint="uvx influxdb-mcp-server",
        permissions_note="Nécessite un jeton InfluxDB ; accès à vos buckets de mesures.",
        official=False,
    ),
    # ============================================ Web, recherche & scraping
    McpCatalogEntry(
        catalog_id="brave-search",
        name="Brave Search",
        description="Recherche web via l'API Brave Search.",
        category="Web, recherche & scraping",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-brave-search",
        permissions_note="Nécessite une clé API Brave ; envoie les requêtes au service Brave.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="google-search",
        name="Google Search",
        description="Recherche web via l'API Google Custom Search.",
        category="Web, recherche & scraping",
        transport="stdio",
        install_hint="npx -y google-search-mcp",
        permissions_note="Nécessite une clé API Google ; envoie les requêtes à Google.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="duckduckgo",
        name="DuckDuckGo",
        description="Recherche web respectueuse de la vie privée via DuckDuckGo.",
        category="Web, recherche & scraping",
        transport="stdio",
        install_hint="uvx duckduckgo-mcp-server",
        permissions_note="Envoie les requêtes de recherche à DuckDuckGo ; sans clé API.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="fetch",
        name="Fetch",
        description="Récupération de pages web et conversion en texte exploitable.",
        category="Web, recherche & scraping",
        transport="stdio",
        install_hint="uvx mcp-server-fetch",
        permissions_note="Effectue des requêtes HTTP sortantes vers les URL demandées.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="puppeteer",
        name="Puppeteer",
        description="Automatisation d'un navigateur Chrome : navigation et captures d'écran.",
        category="Web, recherche & scraping",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-puppeteer",
        permissions_note="Contrôle un navigateur et peut visiter n'importe quel site.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="playwright",
        name="Playwright",
        description="Pilotage d'un navigateur : navigation, clics, captures d'écran.",
        category="Web, recherche & scraping",
        transport="stdio",
        install_hint="npx -y @playwright/mcp@latest",
        permissions_note="Contrôle un navigateur et peut visiter n'importe quel site.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="firecrawl",
        name="Firecrawl",
        description="Extraction et crawl de sites web en contenu structuré Markdown.",
        category="Web, recherche & scraping",
        transport="stdio",
        install_hint="npx -y firecrawl-mcp",
        permissions_note="Nécessite une clé API Firecrawl ; récupère le contenu des sites.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="exa",
        name="Exa",
        description="Recherche web sémantique orientée IA via l'API Exa.",
        category="Web, recherche & scraping",
        transport="stdio",
        install_hint="npx -y exa-mcp-server",
        permissions_note="Nécessite une clé API Exa ; envoie les requêtes au service Exa.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="perplexity",
        name="Perplexity",
        description="Recherche et réponses sourcées via l'API Perplexity (Sonar).",
        category="Web, recherche & scraping",
        transport="stdio",
        install_hint="npx -y @ppl-ai/modelcontextprotocol",
        permissions_note="Nécessite une clé API Perplexity ; envoie vos requêtes au service.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="tavily",
        name="Tavily",
        description="Recherche web et extraction de contenu optimisées pour les agents IA.",
        category="Web, recherche & scraping",
        transport="stdio",
        install_hint="npx -y tavily-mcp",
        permissions_note="Nécessite une clé API Tavily ; envoie vos requêtes au service.",
        official=True,
    ),
    # ==================================================== Cloud & infra
    McpCatalogEntry(
        catalog_id="aws",
        name="AWS",
        description="Accès aux services AWS : documentation, coûts et ressources.",
        category="Cloud & infra",
        transport="stdio",
        install_hint="uvx awslabs.core-mcp-server",
        permissions_note="Utilise vos identifiants AWS ; peut lire et modifier vos ressources.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="gcp",
        name="Google Cloud",
        description="Gestion des ressources Google Cloud : Compute, IAM et facturation.",
        category="Cloud & infra",
        transport="stdio",
        install_hint="uvx gcp-mcp-server",
        permissions_note="Utilise vos identifiants GCP ; peut lire et modifier vos ressources.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="azure",
        name="Azure",
        description="Gestion des ressources Microsoft Azure : abonnements et services.",
        category="Cloud & infra",
        transport="stdio",
        install_hint="npx -y @azure/mcp-server",
        permissions_note="Utilise vos identifiants Azure ; peut lire et modifier vos ressources.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="cloudflare",
        name="Cloudflare",
        description="Gestion des ressources Cloudflare : Workers, DNS et analytics.",
        category="Cloud & infra",
        transport="stdio",
        install_hint="npx -y @cloudflare/mcp-server-cloudflare",
        permissions_note="Nécessite un jeton Cloudflare ; peut modifier votre compte.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="vercel",
        name="Vercel",
        description="Gestion des projets et déploiements Vercel.",
        category="Cloud & infra",
        transport="http",
        install_hint="npx -y mcp-remote https://mcp.vercel.com",
        permissions_note="Authentification Vercel ; peut lire et déclencher des déploiements.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="netlify",
        name="Netlify",
        description="Gestion des sites et déploiements Netlify.",
        category="Cloud & infra",
        transport="stdio",
        install_hint="npx -y @netlify/mcp",
        permissions_note="Nécessite un jeton Netlify ; peut lire et déployer vos sites.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="digitalocean",
        name="DigitalOcean",
        description="Gestion des droplets, bases et App Platform DigitalOcean.",
        category="Cloud & infra",
        transport="stdio",
        install_hint="npx -y @digitalocean/mcp",
        permissions_note="Nécessite un jeton DigitalOcean ; peut modifier vos ressources.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="heroku",
        name="Heroku",
        description="Gestion des applications, dynos et add-ons Heroku.",
        category="Cloud & infra",
        transport="stdio",
        install_hint="npx -y @heroku/mcp-server",
        permissions_note="Nécessite un jeton Heroku ; peut modifier vos applications.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="fly",
        name="Fly.io",
        description="Gestion des applications et machines déployées sur Fly.io.",
        category="Cloud & infra",
        transport="stdio",
        install_hint="npx -y fly-mcp-server",
        permissions_note="Nécessite un jeton Fly.io ; peut modifier vos applications.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="grafana",
        name="Grafana",
        description="Consultation des tableaux de bord, alertes et sources de données Grafana.",
        category="Cloud & infra",
        transport="stdio",
        install_hint="docker run -i --rm mcp/grafana",
        permissions_note="Nécessite un jeton Grafana ; accès à vos tableaux de bord.",
        official=False,
    ),
    # ====================================================== Communication
    McpCatalogEntry(
        catalog_id="slack",
        name="Slack",
        description="Lecture des canaux Slack et envoi de messages.",
        category="Communication",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-slack",
        permissions_note="Nécessite un jeton Slack ; peut lire et publier dans vos canaux.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="discord",
        name="Discord",
        description="Lecture des salons Discord et envoi de messages via un bot.",
        category="Communication",
        transport="stdio",
        install_hint="npx -y discord-mcp-server",
        permissions_note="Nécessite un jeton de bot Discord ; peut lire et publier des messages.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="telegram",
        name="Telegram",
        description="Envoi et lecture de messages via un bot Telegram.",
        category="Communication",
        transport="stdio",
        install_hint="npx -y telegram-mcp-server",
        permissions_note="Nécessite un jeton de bot Telegram ; peut lire et envoyer des messages.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="microsoft-teams",
        name="Microsoft Teams",
        description="Lecture des canaux et envoi de messages dans Microsoft Teams.",
        category="Communication",
        transport="stdio",
        install_hint="npx -y @microsoft/teams-mcp",
        permissions_note="Authentification Microsoft ; peut lire et publier dans vos équipes.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="twilio",
        name="Twilio",
        description="Envoi de SMS et gestion des communications via l'API Twilio.",
        category="Communication",
        transport="stdio",
        install_hint="npx -y @twilio-alpha/mcp",
        permissions_note="Nécessite des identifiants Twilio ; peut envoyer des SMS facturés.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="sendgrid",
        name="SendGrid",
        description="Envoi d'e-mails transactionnels via l'API SendGrid.",
        category="Communication",
        transport="stdio",
        install_hint="uvx sendgrid-mcp",
        permissions_note="Nécessite une clé API SendGrid ; peut envoyer des e-mails.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="gmail",
        name="Gmail",
        description="Lecture, recherche et envoi d'e-mails via Gmail.",
        category="Communication",
        transport="stdio",
        install_hint="npx -y @gongrzhe/server-gmail-autoauth-mcp",
        permissions_note="Authentification Google ; peut lire et envoyer des e-mails.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="outlook",
        name="Outlook",
        description="Lecture, recherche et envoi d'e-mails via Microsoft Outlook.",
        category="Communication",
        transport="stdio",
        install_hint="npx -y outlook-mcp-server",
        permissions_note="Authentification Microsoft ; peut lire et envoyer des e-mails.",
        official=False,
    ),
    # =========================================== Productivité & connaissance
    McpCatalogEntry(
        catalog_id="notion",
        name="Notion",
        description="Lecture et édition de pages et bases de données Notion.",
        category="Productivité & connaissance",
        transport="stdio",
        install_hint="npx -y @notionhq/notion-mcp-server",
        permissions_note="Nécessite un jeton Notion ; peut lire et modifier votre espace.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="confluence",
        name="Confluence",
        description="Recherche et édition de pages dans les espaces Confluence.",
        category="Productivité & connaissance",
        transport="stdio",
        install_hint="uvx mcp-atlassian",
        permissions_note="Nécessite un jeton Atlassian ; peut lire et modifier vos pages.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="obsidian",
        name="Obsidian",
        description="Lecture et écriture de notes dans un coffre Obsidian local.",
        category="Productivité & connaissance",
        transport="stdio",
        install_hint="uvx mcp-obsidian",
        permissions_note="Accès aux fichiers Markdown du coffre Obsidian indiqué.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="todoist",
        name="Todoist",
        description="Gestion des tâches et projets Todoist.",
        category="Productivité & connaissance",
        transport="stdio",
        install_hint="npx -y @abhiz123/todoist-mcp-server",
        permissions_note="Nécessite un jeton Todoist ; peut lire et modifier vos tâches.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="asana",
        name="Asana",
        description="Gestion des tâches, projets et portefeuilles Asana.",
        category="Productivité & connaissance",
        transport="http",
        install_hint="npx -y mcp-remote https://mcp.asana.com/sse",
        permissions_note="Authentification Asana ; peut lire et modifier vos projets.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="trello",
        name="Trello",
        description="Gestion des tableaux, listes et cartes Trello.",
        category="Productivité & connaissance",
        transport="stdio",
        install_hint="npx -y trello-mcp-server",
        permissions_note="Nécessite un jeton Trello ; peut lire et modifier vos tableaux.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="airtable",
        name="Airtable",
        description="Lecture et écriture d'enregistrements dans des bases Airtable.",
        category="Productivité & connaissance",
        transport="stdio",
        install_hint="npx -y airtable-mcp-server",
        permissions_note="Nécessite un jeton Airtable ; peut lire et modifier vos bases.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="google-calendar",
        name="Google Calendar",
        description="Consultation et création d'événements dans Google Agenda.",
        category="Productivité & connaissance",
        transport="stdio",
        install_hint="npx -y @cocal/google-calendar-mcp",
        permissions_note="Authentification Google ; peut lire et modifier votre agenda.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="google-sheets",
        name="Google Sheets",
        description="Lecture et écriture de cellules dans des feuilles Google Sheets.",
        category="Productivité & connaissance",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-google-sheets",
        permissions_note="Authentification Google ; peut lire et modifier vos feuilles.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="google-docs",
        name="Google Docs",
        description="Lecture et édition de documents Google Docs.",
        category="Productivité & connaissance",
        transport="stdio",
        install_hint="npx -y google-docs-mcp",
        permissions_note="Authentification Google ; peut lire et modifier vos documents.",
        official=False,
    ),
    # ============================================== Paiement & business
    McpCatalogEntry(
        catalog_id="stripe",
        name="Stripe",
        description="Gestion des paiements, clients et abonnements Stripe.",
        category="Paiement & business",
        transport="stdio",
        install_hint="npx -y @stripe/mcp",
        permissions_note="Nécessite une clé API Stripe ; peut lire et créer des paiements.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="paypal",
        name="PayPal",
        description="Gestion des paiements, factures et transactions PayPal.",
        category="Paiement & business",
        transport="http",
        install_hint="npx -y mcp-remote https://mcp.paypal.com/sse",
        permissions_note="Authentification PayPal ; peut lire et créer des transactions.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="shopify",
        name="Shopify",
        description="Gestion des produits, commandes et clients d'une boutique Shopify.",
        category="Paiement & business",
        transport="stdio",
        install_hint="npx -y @shopify/dev-mcp",
        permissions_note="Nécessite un jeton Shopify ; peut lire et modifier votre boutique.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="hubspot",
        name="HubSpot",
        description="Gestion des contacts, transactions et pipelines CRM HubSpot.",
        category="Paiement & business",
        transport="http",
        install_hint="npx -y mcp-remote https://mcp.hubspot.com/anthropic",
        permissions_note="Authentification HubSpot ; peut lire et modifier votre CRM.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="salesforce",
        name="Salesforce",
        description="Interrogation et mise à jour des objets CRM Salesforce (SOQL).",
        category="Paiement & business",
        transport="stdio",
        install_hint="uvx salesforce-mcp-server",
        permissions_note="Authentification Salesforce ; peut lire et modifier vos objets.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="quickbooks",
        name="QuickBooks",
        description="Gestion de la comptabilité QuickBooks : factures et transactions.",
        category="Paiement & business",
        transport="stdio",
        install_hint="npx -y quickbooks-mcp-server",
        permissions_note="Authentification Intuit ; peut lire et modifier votre comptabilité.",
        official=False,
    ),
    # ===================================================== IA & données
    McpCatalogEntry(
        catalog_id="memory",
        name="Memory",
        description="Mémoire persistante sous forme de graphe de connaissances.",
        category="IA & données",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-memory",
        permissions_note="Stocke des informations localement entre les sessions.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="knowledge-graph",
        name="Knowledge Graph",
        description="Graphe de connaissances persistant avec mémoire par projet.",
        category="IA & données",
        transport="stdio",
        install_hint="npx -y mcp-knowledge-graph",
        permissions_note="Stocke le graphe localement sur le disque.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="sequential-thinking",
        name="Sequential Thinking",
        description="Aide au raisonnement structuré étape par étape.",
        category="IA & données",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-sequential-thinking",
        permissions_note="Aucun accès sensible : raisonnement en mémoire uniquement.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="huggingface",
        name="Hugging Face",
        description="Recherche de modèles, jeux de données et Spaces sur Hugging Face.",
        category="IA & données",
        transport="stdio",
        install_hint="npx -y @huggingface/mcp-server",
        permissions_note="Un jeton HF permet l'accès à vos dépôts privés ; sinon lecture publique.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="openai",
        name="OpenAI",
        description="Accès aux modèles OpenAI : génération de texte et d'images.",
        category="IA & données",
        transport="stdio",
        install_hint="uvx openai-mcp-server",
        permissions_note="Nécessite une clé API OpenAI ; les appels sont facturés.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="replicate",
        name="Replicate",
        description="Exécution de modèles d'IA hébergés sur Replicate.",
        category="IA & données",
        transport="stdio",
        install_hint="npx -y replicate-mcp",
        permissions_note="Nécessite un jeton Replicate ; les exécutions sont facturées.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="wolfram-alpha",
        name="Wolfram Alpha",
        description="Calculs, mathématiques et connaissances via Wolfram Alpha.",
        category="IA & données",
        transport="stdio",
        install_hint="uvx wolfram-alpha-mcp",
        permissions_note="Nécessite une clé App Wolfram ; envoie vos requêtes au service.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="qdrant",
        name="Qdrant",
        description="Recherche vectorielle et mémoire sémantique via Qdrant.",
        category="IA & données",
        transport="stdio",
        install_hint="uvx mcp-server-qdrant",
        permissions_note="Accès à l'instance Qdrant indiquée ; stocke des vecteurs.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="pinecone",
        name="Pinecone",
        description="Recherche vectorielle gérée dans le cloud via Pinecone.",
        category="IA & données",
        transport="stdio",
        install_hint="npx -y @pinecone-database/mcp",
        permissions_note="Nécessite une clé API Pinecone ; accès à vos index vectoriels.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="chroma",
        name="Chroma",
        description="Base de données vectorielle open source pour la recherche sémantique.",
        category="IA & données",
        transport="stdio",
        install_hint="uvx chroma-mcp",
        permissions_note="Accès à l'instance Chroma indiquée ; stocke des embeddings.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="weaviate",
        name="Weaviate",
        description="Base de données vectorielle Weaviate pour la recherche hybride.",
        category="IA & données",
        transport="stdio",
        install_hint="uvx weaviate-mcp-server",
        permissions_note="Accès à l'instance Weaviate indiquée par les identifiants.",
        official=False,
    ),
    # =================================================== Outils & système
    McpCatalogEntry(
        catalog_id="time",
        name="Time",
        description="Heure courante et conversions de fuseaux horaires.",
        category="Outils & système",
        transport="stdio",
        install_hint="uvx mcp-server-time",
        permissions_note="Aucun accès sensible : lecture de l'horloge système uniquement.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="everything",
        name="Everything",
        description="Serveur de démonstration exposant tous les types de primitives MCP.",
        category="Outils & système",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-everything",
        permissions_note="Serveur de test sans accès à des données sensibles.",
        official=True,
    ),
    McpCatalogEntry(
        catalog_id="shell",
        name="Shell",
        description="Exécution de commandes shell dans un environnement contrôlé.",
        category="Outils & système",
        transport="stdio",
        install_hint="uvx mcp-shell-server",
        permissions_note="Peut exécuter des commandes système : à n'autoriser qu'avec prudence.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="apple-notes",
        name="Apple Notes",
        description="Lecture et création de notes dans l'app Notes de macOS.",
        category="Outils & système",
        transport="stdio",
        install_hint="uvx apple-notes-mcp",
        permissions_note="Accès local à vos notes Apple ; macOS uniquement.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="spotify",
        name="Spotify",
        description="Contrôle de la lecture Spotify et recherche de titres et playlists.",
        category="Outils & système",
        transport="stdio",
        install_hint="npx -y spotify-mcp-server",
        permissions_note="Authentification Spotify ; peut contrôler votre lecture.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="youtube",
        name="YouTube",
        description="Recherche de vidéos et récupération de transcriptions YouTube.",
        category="Outils & système",
        transport="stdio",
        install_hint="npx -y youtube-mcp-server",
        permissions_note="Requêtes vers l'API YouTube ; une clé étend les quotas.",
        official=False,
    ),
    McpCatalogEntry(
        catalog_id="maps",
        name="Google Maps",
        description="Géocodage, itinéraires et recherche de lieux via Google Maps.",
        category="Outils & système",
        transport="stdio",
        install_hint="npx -y @modelcontextprotocol/server-google-maps",
        permissions_note="Nécessite une clé API Google Maps ; envoie vos requêtes à Google.",
        official=True,
    ),
)

CATALOG_BY_ID: Final[dict[str, McpCatalogEntry]] = {
    entry.catalog_id: entry for entry in CATALOG
}


def categories() -> list[str]:
    """Ordered list of catalog categories for the marketplace UI."""
    return list(CATEGORIES)
