"""Runtime configuration.

All settings come from ``ELYSIUM_*`` environment variables, injected by the
Rust core when it spawns this engine as a sidecar (see ARCHITECTURE.md §2).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from pydantic import Field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


def default_data_dir() -> Path:
    """Platform application-data directory for Elysium."""
    if sys.platform == "win32":
        base = Path(os.environ.get("APPDATA", str(Path.home() / "AppData" / "Roaming")))
        return base / "elysium"
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "elysium"
    xdg = os.environ.get("XDG_DATA_HOME")
    base = Path(xdg) if xdg else Path.home() / ".local" / "share"
    return base / "elysium"


def default_db_url(data_dir: Path) -> str:
    """SQLite file in the data dir — the zero-setup default (ADR-001)."""
    return f"sqlite:///{data_dir / 'elysium.db'}"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="ELYSIUM_", extra="ignore")

    token: str = Field(description="Session token generated by the Rust core; required.")
    port: int = 8791
    data_dir: Path = Field(default_factory=default_data_dir)
    db_url: str = Field(
        default="",
        description="SQLAlchemy URL. Empty -> SQLite in data_dir; postgresql://... -> Postgres.",
    )

    @model_validator(mode="after")
    def _resolve_db_url(self) -> "Settings":
        if not self.db_url:
            self.db_url = default_db_url(self.data_dir)
        return self

    @property
    def is_postgres(self) -> bool:
        return self.db_url.startswith("postgresql")
